type tb_bill_define={ readonly id:number,readonly name:string,readonly type:number,readonly icon:number,readonly platform:number,readonly title:string,readonly is_valid:number,readonly order_num:number,readonly money:number,readonly money_game:number,readonly money_first_gift:number,readonly money_first_gift_desc:string,readonly money_gift:number,readonly money_gift_desc:string,readonly charge_type:number,readonly month_card_id:number,readonly remark:string};
class tb_bill {
	static readonly tb_bill_define:{[key:number]:tb_bill_define} = {
		[1]:{id:1 , name:'官网' , type:0 , icon:1 , platform:1 , title:'60元宝' , is_valid:1 , order_num:7 , money:6 , money_game:60 , money_first_gift:60 , money_first_gift_desc:'额外赠送60元宝（限购1次）' , money_gift:6 , money_gift_desc:'额外赠送6元宝' , charge_type:1 , month_card_id:0 , remark:'7'},
		[2]:{id:2 , name:'官网' , type:0 , icon:4 , platform:1 , title:'300元宝礼包' , is_valid:1 , order_num:1 , money:30 , money_game:300 , money_first_gift:0 , money_first_gift_desc:'每天赠送150元宝，有效期30天' , money_gift:0 , money_gift_desc:'每天赠送150元宝，有效期29天' , charge_type:1 , month_card_id:1 , remark:'1'},
		[3]:{id:3 , name:'官网' , type:0 , icon:2 , platform:1 , title:'300元宝' , is_valid:1 , order_num:6 , money:30 , money_game:300 , money_first_gift:300 , money_first_gift_desc:'额外赠送300元宝（限购1次）' , money_gift:33 , money_gift_desc:'额外赠送33元宝' , charge_type:1 , month_card_id:0 , remark:'6'},
		[4]:{id:4 , name:'官网' , type:0 , icon:2 , platform:1 , title:'980元宝' , is_valid:1 , order_num:5 , money:98 , money_game:980 , money_first_gift:980 , money_first_gift_desc:'额外赠送980元宝（限购1次）' , money_gift:118 , money_gift_desc:'额外赠送118元宝' , charge_type:1 , month_card_id:0 , remark:'5'},
		[5]:{id:5 , name:'官网' , type:0 , icon:2 , platform:1 , title:'1980元宝' , is_valid:1 , order_num:4 , money:198 , money_game:1980 , money_first_gift:1980 , money_first_gift_desc:'额外赠送1980元宝（限购1次）' , money_gift:258 , money_gift_desc:'额外赠送258元宝' , charge_type:1 , month_card_id:0 , remark:'4'},
		[6]:{id:6 , name:'官网' , type:0 , icon:3 , platform:1 , title:'3280元宝' , is_valid:1 , order_num:3 , money:328 , money_game:3280 , money_first_gift:3280 , money_first_gift_desc:'额外赠送3280元宝（限购1次）' , money_gift:458 , money_gift_desc:'额外赠送458元宝' , charge_type:1 , month_card_id:0 , remark:'3'},
		[7]:{id:7 , name:'官网' , type:0 , icon:3 , platform:1 , title:'6480元宝' , is_valid:1 , order_num:2 , money:648 , money_game:6480 , money_first_gift:6480 , money_first_gift_desc:'额外赠送6480元宝（限购1次）' , money_gift:978 , money_gift_desc:'额外赠送978元宝' , charge_type:1 , month_card_id:0 , remark:'2'}
	};
}